#! /usr/bin/env python

import sys
import os
from scraper.src.index import run_config
import requests, json

HOST_URL = os.environ.get('MEILISEARCH_HOST_URL')
API_KEY = os.environ.get('MEILISEARCH_API_KEY')

if HOST_URL is None or API_KEY is None:
    print("Error: MEILISEARCH_HOST_URL and MEILISEARCH_API_KEY environment variables are required.")
    sys.exit(1)

DOMAIN=os.environ.get('CN_OPENJIANGHU_ORG_DOMAIN')
print(DOMAIN+": public 文章抓取开始")
run_config('./config/cn_openjianghu_org_doc_public.json', None)
