#! /usr/bin/env python

import sys
import os
from scraper.src.index import run_config
import requests, json

HOST_URL = os.environ.get('MEILISEARCH_HOST_URL')
API_KEY = os.environ.get('MEILISEARCH_API_KEY')

DOMAIN=os.environ.get('OPENJIANGHU_ORG_DOMAIN')
print(DOMAIN+": public 文章抓取开始")
run_config('./config/openjianghu_org_doc_public.json', None)
