#! /usr/bin/env python

import sys
import os
from scraper.src.index import run_config
import requests, json

HOST_URL = os.environ.get('MEILISEARCH_HOST_URL')
API_KEY = os.environ.get('MEILISEARCH_API_KEY')

if HOST_URL is None or API_KEY is None:
    print("Error: MEILISEARCH_HOST_URL and MEILISEARCH_API_KEY environment variables are required.")
    sys.exit(1)


def getAuthToken(domain, userId, password):
    print(domain + '/doc/resource')
    response = requests.post(domain + '/doc/resource',
        headers={ 'content-type': 'application/json; charset=utf-8', 'Accept': 'application/json' },
        json={
            'packageId': '123456',
            'packageType': 'httpRequest',
            'appData': {
                'appId': 'doc',
                'pageId': 'login',
                'actionId': 'passwordLogin',
                'userAgent': 'docs-scraper',
                'actionData': {
                    'userId': userId,
                    'password': password,
                    'deviceId': 'docs-scraper',
                },
            }
        }
    )
    if response.status_code != 200:
        print("登录失败: " + response.text)
        sys.exit(1)
    response_body = json.loads(response.text)
    if response_body.get('status') != 'success':
        print("登录失败 status: " + response_body.get('status'))
        sys.exit(1)

    authToken = response_body.get('appData').get('resultData').get('authToken')
    print("登录成功")
    return authToken

DOMAIN=os.environ.get('OPENJIANGHU_ORG_DOMAIN')
USERID=os.environ.get('OPENJIANGHU_ORG_USERID')
PASSWORD=os.environ.get('OPENJIANGHU_ORG_PASSWORD')

print(DOMAIN+": all 文章抓取开始")
authToken = getAuthToken(domain=DOMAIN, userId=USERID, password=PASSWORD)
run_config('./config/openjianghu_org_doc_all.json', authToken)
